### ISSUE TITLE
Rename this repository as 'schema-2016' and make new 'schema' repository with 2020 schema

### ISSUE THREAD

**Issue by tgraham-antenna** [Schematron/schema-2016#21]
The first 'schema' repository was similarly renamed as 'schema-2006' after ISO Schematron (2016) was released, when this 'schema' repository was created for the 2016 schema.

A separate repository makes it easier to keep the issues separate.

**Comment by AndrewSales** [comment]
Done, but some issues raised here - e.g. #19 - will need replicating elsewhere as a result.
